FROM golang:alpine AS build-env
RUN apk --no-cache add build-base git gcc
ADD . /src
RUN cd /src && go build -o apimock


FROM alpine
WORKDIR /app
COPY --from=build-env /src/apimock /app/

EXPOSE 8080

RUN mkdir -p /app/mocks

CMD ["/app/apimock", "proxy", "-a", ":8888", "--k8s"]